export const wzryArea = [
  { id: 0, title: '全部', servers: [] },
  { id: 2, title: '安卓QQ', servers: [] },
  { id: 3, title: '安卓微信', servers: [] },
  { id: 5, title: '苹果微信', servers: [] },
  { id: 4, title: '苹果QQ', servers: [] },
]

export const wzryPropertySearch = [
  {
    id: 5,
    title: '皮肤数',
    type: 'radio',
    is_required: 'N',
    course_img: '',
    val: [
      { id: 159, title: '0-50' },
      { id: 161, title: '51-100' },
      { id: 162, title: '101-150' },
      { id: 163, title: '151-200' },
      { id: 164, title: '201-250' },
      { id: 165, title: '251-300' },
      { id: 166, title: '301-310' },
      { id: 4520, title: '311-320' },
      { id: 4521, title: '321-330' },
      { id: 4522, title: '331-340' },
      { id: 4523, title: '341-350' },
      { id: 4524, title: '351-360' },
      { id: 4525, title: '361-370' },
      { id: 4526, title: '371-380' },
      { id: 4527, title: '381-390' },
      { id: 4528, title: '391-400' },
      { id: 4529, title: '401-410' },
      { id: 4530, title: '411-420' },
      { id: 4531, title: '421-500' },
    ],
  },
  {
    id: 4,
    title: '英雄数',
    type: 'radio',
    is_required: 'N',
    course_img: '',
    val: [
      { id: 167, title: '0-50' },
      { id: 168, title: '51-100' },
      { id: 169, title: '101-150' },
    ],
  },
  {
    id: 29,
    title: '贵族等级',
    type: 'radio',
    is_required: 'N',
    course_img: '',
    val: [
      { id: 176, title: 'V1' },
      { id: 177, title: 'V2' },
      { id: 178, title: 'V3' },
      { id: 179, title: 'V4' },
      { id: 180, title: 'V5' },
      { id: 181, title: 'V6' },
      { id: 182, title: 'V7' },
      { id: 183, title: 'V8' },
      { id: 184, title: 'V9' },
      { id: 185, title: 'V10' },
    ],
  },
  {
    id: 12,
    title: '实名',
    type: 'radio',
    is_required: 'Y',
    course_img: 'https://file.kejinshou.com/default/202109/22/14/38057R1DBAC8.png',
    val: [
      { id: 1102, title: '有实名修改机会/实名是本人' },
      { id: 1103, title: '有实名修改机会/实名不是本人' },
      { id: 1101, title: '无实名修改机会/实名是本人' },
      { id: 358, title: '无实名修改机会/实名不是本人' },
      { id: 1110, title: '已删实名随时可以认证' },
    ],
  },
  {
    id: 26,
    title: '稀有英雄',
    type: 'checkbox',
    is_required: 'N',
    course_img: '',
    val: [
      { id: 20, title: '嬴政' },
      { id: 21, title: '韩信' },
      { id: 22, title: '夏洛特' },
      { id: 23, title: '艾琳' },
      { id: 24, title: '橘右京' },
      { id: 25, title: '娜可露露' },
      { id: 26, title: '不知火舞' },
      { id: 27, title: '赵云' },
      { id: 1389, title: '金蝉' },
      { id: 3577, title: '戈娅' },
    ],
  },
  {
    id: 1,
    title: '荣耀水晶',
    type: 'checkbox',
    is_required: 'N',
    course_img: '',
    val: [
      { id: 28, title: '武则天' },
      { id: 31, title: '倪克斯神谕' },
      { id: 29, title: '天鹅之梦' },
      { id: 30, title: '星空梦想' },
      { id: 33, title: '无限飓风号' },
      { id: 35, title: '活力突击' },
      { id: 40, title: '杀手不太冷' },
      { id: 41, title: '大秦宣太后' },
      { id: 43, title: '鸣剑·曳影' },
      { id: 46, title: '全息碎影' },
      { id: 2229, title: '星域神启' },
      { id: 3578, title: '九霄神辉' },
      { id: 5032, title: '赤影疾锋' },
      { id: 8025, title: '银白咏叹调' },
      { id: 9518, title: '幻阙歌' },
    ],
  },
  {
    id: 2,
    title: '星传说',
    type: 'checkbox',
    is_required: 'N',
    course_img: '',
    val: [
      { id: 64, title: '幻海之心' },
      { id: 67, title: '未来机甲' },
      { id: 70, title: '幽冥之眼' },
      { id: 80, title: '零号·雷霆' },
      { id: 83, title: '幽冥火' },
      { id: 85, title: '金色仲夏夜' },
      { id: 36, title: '时之愿境' },
      { id: 3531, title: '时之羁绊' },
      { id: 3532, title: '时之思念' },
      { id: 3564, title: '星际治安官' },
      { id: 7962, title: '黛羽霜翎' },
    ],
  },
  {
    id: 3,
    title: '传说皮肤',
    type: 'checkbox',
    is_required: 'N',
    course_img: '',
    val: [
      { id: 37, title: '黄金狮子座' },
      { id: 39, title: '黄金射手座' },
      { id: 56, title: '黄金白羊座' },
      { id: 75, title: '零号·赤焰' },
      { id: 69, title: '地狱火' },
      { id: 71, title: '仲夏夜之梦' },
      { id: 77, title: '海洋之心' },
      { id: 78, title: '地狱之眼' },
      { id: 68, title: '末日机甲-孙尚香' },
      { id: 65, title: '云霓雀翎' },
      { id: 63, title: '一念神魔' },
      { id: 194, title: '淬星耀世' },
      { id: 42, title: '冠军飞将' },
      { id: 59, title: '久胜战神' },
      { id: 58, title: '猫影幻舞' },
      { id: 44, title: '云鹰飞将' },
      { id: 61, title: '炽阳神光' },
      { id: 193, title: '游龙清影' },
      { id: 3551, title: '无双飞将' },
      { id: 73, title: '音你心动-小乔' },
      { id: 82, title: '音你心动-周瑜' },
      { id: 87, title: '胖达荣荣' },
      { id: 88, title: '李逍遥' },
      { id: 90, title: '乞巧织情' },
      { id: 94, title: '时之恋人-刘备' },
      { id: 79, title: '飞鸢探春' },
      { id: 50, title: '绛天战甲' },
      { id: 1126, title: '超时空战士' },
      { id: 1127, title: '遇见胡旋' },
      { id: 2343, title: '末日机甲' },
      { id: 2346, title: '花朝如约' },
      { id: 3497, title: '挚爱之约' },
      { id: 3498, title: '挚爱花嫁' },
      { id: 4549, title: '音你闪耀' },
      { id: 4630, title: '碎云' },
      { id: 5033, title: '天启幻梦' },
      { id: 7930, title: '神器·狴犴令' },
      { id: 9455, title: '神器·明辉仪' },
      { id: 9519, title: '山海·炽霜斩' },
      { id: 9521, title: '山海·琳琅生' },
      { id: 9522, title: '山海·苍雷引' },
    ],
  },
  {
    id: 27,
    title: '限定皮肤',
    type: 'checkbox',
    is_required: 'N',
    course_img: '',
    val: [
      { id: 9566, title: '齐天大圣' },
      { id: 8003, title: '诗剑行' },
      { id: 8026, title: '怒海麟威' },
      { id: 8004, title: '降魔' },
      { id: 62, title: '冰锋战神' },
      { id: 84, title: '游园惊梦' },
      { id: 66, title: '遇见飞天' },
      { id: 86, title: '梁祝' },
      { id: 72, title: '李小龙' },
      { id: 5828, title: '五谷丰年' },
      { id: 1128, title: '高山流水' },
      { id: 76, title: '奔雷神使' },
      { id: 81, title: '祈雪灵祝' },
      { id: 89, title: '御风骁将' },
      { id: 92, title: '时雨天司' },
      { id: 111, title: '天狼溯光者' },
      { id: 127, title: '天狼征服者' },
      { id: 131, title: '天狼狩猎者' },
      { id: 133, title: '天狼运算者' },
      { id: 139, title: '天狼绘梦者' },
      { id: 128, title: '逐梦之音' },
      { id: 130, title: '逐梦之翼' },
      { id: 134, title: '逐梦之星' },
      { id: 135, title: '逐梦之影' },
      { id: 3474, title: '匿光决锋者' },
      { id: 137, title: '逐梦之光' },
      { id: 95, title: '龙胆' },
      { id: 98, title: '武圣' },
      { id: 100, title: '烈魂' },
      { id: 115, title: '神威' },
      { id: 112, title: '虎魄' },
      { id: 120, title: '幽恒' },
      { id: 109, title: '岱宗' },
      { id: 123, title: '飞衡' },
      { id: 107, title: '玄嵩' },
      { id: 126, title: '太华' },
      { id: 143, title: '白虎志' },
      { id: 144, title: '青龙志' },
      { id: 145, title: '瑞麟志' },
      { id: 146, title: '玄武志' },
      { id: 147, title: '朱雀志' },
      { id: 118, title: '永曜之星' },
      { id: 103, title: '辉光之辰' },
      { id: 148, title: '凤凰于飞' },
      { id: 140, title: '凤求凰' },
      { id: 150, title: '如梦令-嫦娥' },
      { id: 157, title: '如梦令-后羿' },
      { id: 190, title: '霸王别姬-项羽' },
      { id: 191, title: '霸王别姬-虞姬' },
      { id: 1129, title: '圣诞老人' },
      { id: 122, title: '奇迹圣诞' },
      { id: 153, title: '默契交锋-兰陵王' },
      { id: 160, title: '默契交锋-花木兰' },
      { id: 154, title: '真爱至上' },
      { id: 151, title: '纯白花嫁' },
      { id: 1130, title: '孙行者' },
      { id: 1131, title: '猪悟能' },
      { id: 155, title: '一生所爱' },
      { id: 158, title: '大圣娶亲' },
      { id: 93, title: '引擎之心' },
      { id: 113, title: '天魔缭乱' },
      { id: 108, title: '白晶晶' },
      { id: 101, title: '魔法小厨娘' },
      { id: 129, title: '青春决赛季' },
      { id: 132, title: '冰霜恋舞曲' },
      { id: 149, title: '梅西' },
      { id: 96, title: '白鹤梁神女' },
      { id: 91, title: '云端筑梦师' },
      { id: 125, title: '乒乒小将' },
      { id: 121, title: '时之彼端' },
      { id: 116, title: '蜜橘之夏' },
      { id: 136, title: '热情桑巴' },
      { id: 138, title: '神奇女侠' },
      { id: 142, title: '美猴王' },
      { id: 152, title: '至尊宝' },
      { id: 156, title: '武陵仙君' },
      { id: 104, title: '异界灵契' },
      { id: 1795, title: '匿光追影者' },
      { id: 1796, title: '女儿国国王' },
      { id: 2158, title: '傲雪梅枪' },
      { id: 141, title: '寅虎·御盾' },
      { id: 186, title: '寅虎·瑞焰' },
      { id: 2207, title: '寅虎·展翼' },
      { id: 2206, title: '寅虎·心曲' },
      { id: 2205, title: '寅虎·赤拳' },
      { id: 2309, title: '时之祈愿-云中君' },
      { id: 2310, title: '时之祈愿-瑶' },
      { id: 2344, title: '补天' },
      { id: 2363, title: '百木心枪' },
      { id: 2364, title: '玉兔公主' },
      { id: 3440, title: '启示之音' },
      { id: 3610, title: '无尽星芒' },
      { id: 3625, title: '深海之息' },
      { id: 4516, title: '唐三藏' },
      { id: 4552, title: '前尘镜' },
      { id: 4606, title: '枫霜尽' },
      { id: 4614, title: '匿光启智者' },
      { id: 5514, title: '时之奇旅' },
      { id: 5726, title: '星穹之声' },
      { id: 5829, title: '绯月行' },
      { id: 7923, title: '神器·万象笔' },
      { id: 7932, title: '天降福星' },
      { id: 7933, title: '梦圆繁星' },
      { id: 9523, title: '山海·玄木引' },
      { id: 9524, title: '冰霜神邸' },
      { id: 9525, title: '山海·碧波行' },
    ],
  },
  {
    id: 28,
    title: '史诗皮肤',
    type: 'checkbox',
    is_required: 'N',
    course_img: '',
    val: [
      { id: 48, title: '电玩小子' },
      { id: 54, title: '苍穹之光' },
      { id: 34, title: '暗夜猫娘' },
      { id: 1132, title: '龙骑士' },
      { id: 38, title: '白蛇' },
      { id: 57, title: '青蛇' },
      { id: 45, title: '魅语' },
      { id: 49, title: '晚萤' },
      { id: 47, title: '无限星赏官' },
      { id: 53, title: '偶像歌手' },
      { id: 60, title: '冰冠公主' },
      { id: 51, title: '末日机甲-吕布' },
      { id: 97, title: '猫狗日记-孙策' },
      { id: 99, title: '猫狗日记-大乔' },
      { id: 117, title: '时之恋人-孙尚香' },
      { id: 106, title: '乱世虎臣' },
      { id: 110, title: '黄金分割率' },
      { id: 114, title: '白龙吟' },
      { id: 119, title: '紫霞仙子' },
      { id: 175, title: '节奏热浪' },
      { id: 192, title: '修罗' },
      { id: 1133, title: '女仆咖啡' },
      { id: 1134, title: '摇滚巨星' },
      { id: 1135, title: '水果甜心' },
      { id: 1136, title: '绅士熊喵' },
      { id: 1137, title: '天才门将' },
      { id: 1378, title: '星夜王子' },
      { id: 1138, title: '心灵骇客' },
      { id: 1379, title: '时之奇旅' },
      { id: 1139, title: '功夫厨神' },
      { id: 1140, title: '德古拉伯爵' },
      { id: 1141, title: '暗隐猎兽者' },
      { id: 1142, title: '幽灵船长' },
      { id: 1143, title: '鬼剑武藏' },
      { id: 1380, title: '暗渊魔法' },
      { id: 1144, title: '心灵战警' },
      { id: 1145, title: '乐园奇幻夜' },
      { id: 1146, title: '天秀·启明' },
      { id: 1147, title: '舞动绿茵' },
      { id: 1148, title: '地狱岩魂' },
      { id: 1149, title: '诗语江南' },
      { id: 1150, title: '纤云弄巧' },
      { id: 1151, title: '繁星吟游' },
      { id: 1675, title: '拒霜思' },
      { id: 1152, title: '缤纷独角兽' },
      { id: 1153, title: '乘风破浪' },
      { id: 102, title: '逐浪之夏' },
      { id: 32, title: '龙鼓争鸣' },
      { id: 1154, title: '月团寄思' },
      { id: 1155, title: '水晶猎龙者' },
      { id: 1156, title: '曙光守护者' },
      { id: 105, title: '遇见神鹿' },
      { id: 1157, title: '热力回旋' },
      { id: 124, title: '箭羽风息' },
      { id: 3475, title: '唤灵魅影' },
      { id: 1158, title: '金属风暴' },
      { id: 1381, title: '原初追遂者' },
      { id: 1159, title: '圣诞狂欢' },
      { id: 1160, title: '圣诞恋歌' },
      { id: 1162, title: '鹰眼护卫' },
      { id: 1163, title: '特工魅影' },
      { id: 1164, title: '王者之锤' },
      { id: 1165, title: '暗夜贵公子' },
      { id: 1166, title: '魅力维加斯' },
      { id: 2156, title: '千年之狐' },
      { id: 1850, title: '黎明之约' },
      { id: 2288, title: '雪上飞焰' },
      { id: 2347, title: '永昼' },
      { id: 3144, title: '赏金猎手' },
      { id: 3331, title: '奇遇舞章' },
      { id: 3563, title: '天秀·音浪' },
      { id: 5101, title: '天秀幻梦' },
      { id: 5513, title: '滕王阁序' },
      { id: 3608, title: '千筹问战' },
      { id: 7928, title: '顽趣' },
      { id: 7931, title: '无心' },
    ],
  },
  {
    id: 160,
    title: '内测皮肤',
    type: 'checkbox',
    is_required: 'N',
    course_img: '',
    val: [
      { id: 1117, title: '优雅恋人' },
      { id: 1118, title: '蔷薇恋人' },
      { id: 1119, title: '女武神' },
      { id: 1120, title: '玩趣恶龙' },
    ],
  },
  {
    id: 164,
    title: '赛季/战令皮肤',
    type: 'checkbox',
    is_required: 'N',
    course_img: '',
    val: [
      { id: 8014, title: '海盐诗旅' },
      { id: 8011, title: '顽趣' },
      { id: 8013, title: '星界游侠' },
      { id: 8012, title: '暖冬·兔眠' },
      { id: 1167, title: '狮心王' },
      { id: 1168, title: '蜃楼王' },
      { id: 1169, title: '妖精王' },
      { id: 1170, title: '炼金王' },
      { id: 1171, title: '凯尔特女王' },
      { id: 1172, title: '狰' },
      { id: 1173, title: '饕餮' },
      { id: 1174, title: '烛龙' },
      { id: 1175, title: '重明' },
      { id: 1176, title: '穷奇' },
      { id: 1177, title: '御狮' },
      { id: 1178, title: '御霄' },
      { id: 1179, title: '御旌' },
      { id: 1180, title: '御銮' },
      { id: 1181, title: '朔风刀' },
      { id: 1182, title: '混沌棋' },
      { id: 1183, title: '疑决卦' },
      { id: 1184, title: '醍醐杖' },
      { id: 1185, title: '原初探秘者' },
      { id: 1186, title: '万华元夜' },
      { id: 1187, title: '演武夺筹' },
      { id: 1188, title: '驱傩正仪' },
      { id: 1189, title: '千军破阵' },
      { id: 1190, title: '猎兽之王' },
      { id: 1191, title: '白昼王子' },
      { id: 1192, title: '朔望之晖' },
      { id: 1193, title: '蓝屏警告' },
      { id: 1194, title: '神迹守卫（钟馗）' },
      { id: 1195, title: '狮舞东方' },
      { id: 1196, title: '赤莲之焰' },
      { id: 1197, title: '驯魔猎人' },
      { id: 1198, title: '星空之诺' },
      { id: 1199, title: '银河之约' },
      { id: 1200, title: '夺宝奇兵' },
      { id: 1201, title: '迷踪丽影' },
      { id: 1202, title: '西部大镖客（猪八戒）' },
      { id: 1203, title: '暗影游猎' },
      { id: 1204, title: '单词大作战' },
      { id: 1205, title: '狂想玩偶喵' },
      { id: 1206, title: '潮玩骑士王' },
      { id: 1207, title: '云间偶戏' },
      { id: 1208, title: '星际陆战队（达摩）' },
      { id: 1209, title: '胡桃异想国' },
      { id: 1210, title: '神迹守卫（墨子）' },
      { id: 1382, title: '航海奇遇记' },
      { id: 1383, title: '圣弓游侠' },
      { id: 1384, title: '真爱魔法' },
      { id: 1847, title: '火炮绅士' },
      { id: 1848, title: '沙漠行僧' },
      { id: 1849, title: '幻夜卜梦' },
      { id: 3332, title: '吟游魔法' },
      { id: 3333, title: '夜都怪侠' },
      { id: 3334, title: '金庭之子' },
      { id: 3574, title: '电玩高手' },
      { id: 3575, title: '午后时光' },
      { id: 3576, title: '大漠名商' },
      { id: 5025, title: '云中旅人' },
      { id: 5026, title: '超时空战士' },
      { id: 5027, title: '落雪兰心' },
    ],
  },
]
